apiVersion: v1
kind: Service
metadata:
  name: {{ include "dgpj-ingestion.fullname" . }}
  labels:
    {{- include "dgpj-ingestion.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    {{- include "dgpj-ingestion.selectorLabels" . | nindent 4 }}
