apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dgpj-frontend.fullname" . }}
  labels:
    {{- include "dgpj-frontend.labels" . | nindent 4 }}
  annotations:
    {{- if and .Values.downscaler (hasKey .Values.downscaler "enabled") (eq .Values.downscaler.enabled true) }}
    downscaler/downscale-period: "{{ .Values.downscaler.downscalePeriod }}"
    {{- else }}
    downscaler/disabled: "true"
    {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dgpj-frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dgpj-frontend.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dgpj-frontend.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ENV_NAME
              value: "{{ .Values.envName }}"
            - name: BACKEND_API_KEY
              valueFrom:
                secretKeyRef:
                  name: dgpj-frontend-secrets
                  key: backend_api_key
            - name: FASTAPI_HEALTH_URL
              valueFrom:
                secretKeyRef:
                  name: dgpj-frontend-secrets
                  key: fastapi_health_url
            - name: FASTAPI_URL
              valueFrom:
                secretKeyRef:
                  name: dgpj-frontend-secrets
                  key: fastapi_url
            - name: FRONTEND_USER_KEY
              valueFrom:
                secretKeyRef:
                  name: dgpj-frontend-secrets
                  key: frontend_user_key
            
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
