{{- if and (hasKey .Values "externalSecrets") (get .Values.externalSecrets "enabled") }}
{{- range .Values.externalSecrets.secrets }}
apiVersion: {{ .apiVersion }}
kind: {{ .kind }}
metadata:
  name: {{ .metadata.name }}
  namespace: {{ .metadata.namespace }}
spec:
  refreshInterval: {{ .refreshInterval }}
  secretStoreRef:
    name: {{ .secretStoreRef.name }}
    kind: {{ .secretStoreRef.kind }}
  target:
    name: {{ .target.name }}
    creationPolicy: {{ .target.creationPolicy }}
  data:
    {{- range .data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
        property: {{ .remoteRef.property }}
    {{- end }}
{{- end }}
{{- end }}
